Exercicios Aula 7 - Numpy e Pandas

In [1]:
#exercicio 1 
#Crie um array NumPy com 10 elementos inteiros aleatorios no intervalo [0,100] e exiba os valores e o tipo de dado do array

import numpy as np

#Escreve valores aleatorios
array_aleatorio = np.random.randint(0, 101, size=10)

print("Valores do array:", array_aleatorio)
print("Tipo de dado do array:", array_aleatorio.dtype)

Valores do array: [ 2 26  6 69 40 30 23 15 79 50]
Tipo de dado do array: int32


In [2]:
#exercicio 2 - matriz de 5x5 com valores aleatorios de [0,1)
#Crie uma matriz de 5x5 com valores aleatorios de [0,1) e encontre o valor minimo, máximo e a media da matriz

import numpy as np

#Criacao da matriz
matriz_numpy = np.random.rand(5, 5)

#Calculos
minimo_numpy = np.min(matriz_numpy)
maximo_numpy = np.max(matriz_numpy)
media_numpy = np.mean(matriz_numpy)

print("Matriz NumPy:")
print(matriz_numpy)
print(f"Mínimo: {minimo_numpy}")
print(f"Máximo: {maximo_numpy}")
print(f"Média: {media_numpy}")

Matriz NumPy:
[[0.98444131 0.72143534 0.35641386 0.83011401 0.20725933]
 [0.69352647 0.95607687 0.36169378 0.76477212 0.09646236]
 [0.72715927 0.12746268 0.02797704 0.31174613 0.74030848]
 [0.22527421 0.80282266 0.02088764 0.70162522 0.26968763]
 [0.91763696 0.47520968 0.53324795 0.19095523 0.88849596]]
Mínimo: 0.0208876445026136
Máximo: 0.9844413104316502
Média: 0.5173076875553997


In [3]:
#exercicio 3 - Criar um array com 10 elementos aleatorio no intervalo [0,1]
#Crie um array com 10 elementos aleatorio no intervalo [0,1]. Em seguida, crie um novo array com os elementos do primeiro array com os elementos do primeiro array multiplicados por 10 e convertidos para inteiro.
import numpy as np

# Criar um array com valores aleatorios
array_original = np.random.rand(10)

# Criar um novo array 
array_novo = (array_original * 10).astype(int)


print("Array Original:")
print(array_original)
print("\nArray Novo:")
print(array_novo)

Array Original:
[0.5261241  0.18974197 0.64229622 0.25825565 0.2021412  0.95409357
 0.77045681 0.87880045 0.74703092 0.60916846]

Array Novo:
[5 1 6 2 2 9 7 8 7 6]


In [6]:
#exercicio 4 - array de duas dimensões com shape (3,3)
#Crie um array de duas dimensões com shape (3,3) e valores aleatórios inteiros no intervalo [0,9]. Substitua todos os elementos da segunda linha por -1.
import numpy as np
import pandas as pd

array = np.random.randint(0, 10, size=(3, 3))

array[1, :] = -1

print("Array de duas dimensões:")
print(array)


Array de duas dimensões:
[[ 9  6  2]
 [-1 -1 -1]
 [ 5  4  9]]

DataFrame:
    fruta  preco  quantidade
0  Banana    7.9          12
1    Maca   10.2           3
2    Pera   11.8           4


In [9]:

#exercicio 5 - DataFrame
#Crie um DataFrame com as seguintes informações....
data = {
    "fruta": ["Banana", "Maca", "Pera"],
    "preco": [7.90, 10.20, 11.80],
    "quantidade": [12, 3, 4]
}
df = pd.DataFrame(data)

print("\nDataFrame:")
print(df)


DataFrame:
    fruta  preco  quantidade
0  Banana    7.9          12
1    Maca   10.2           3
2    Pera   11.8           4
